import html
import re
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (PageBreak, Paragraph, SimpleDocTemplate,
                                Spacer, Table, TableStyle)


class PDFReportGenerator:
    """
    Generates a professional AURA AI fraud investigation PDF.

    The generator sanitizes Unicode characters that are not reliably
    supported by ReportLab's default Helvetica font.
    """

    def __init__(self, output_dir="reports"):

        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.styles = getSampleStyleSheet()

        # ---------------------------------------------------------
        # STYLES
        # ---------------------------------------------------------

        self.title_style = ParagraphStyle(
            "AURATitle",
            parent=self.styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            alignment=TA_CENTER,
            spaceAfter=8,
        )

        self.subtitle_style = ParagraphStyle(
            "AURASubtitle",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            alignment=TA_CENTER,
            textColor=colors.grey,
            spaceAfter=20,
        )

        self.heading_style = ParagraphStyle(
            "AURAHeading",
            parent=self.styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            spaceBefore=12,
            spaceAfter=8,
        )

        self.body_style = ParagraphStyle(
            "AURABody",
            parent=self.styles["BodyText"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=14,
            spaceAfter=6,
        )

        self.small_style = ParagraphStyle(
            "AURASmall",
            parent=self.styles["BodyText"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            spaceAfter=4,
        )

    # =========================================================
    # TEXT SANITIZATION
    # =========================================================

    @staticmethod
    def _sanitize_text(value):
        """
        Convert problematic Unicode characters into characters
        supported by the standard ReportLab Helvetica font.

        This prevents black boxes / missing-glyph symbols in PDFs.
        """

        if value is None:
            return ""

        text = str(value)

        replacements = {
            # Dashes
            "\u2010": "-",   # hyphen
            "\u2011": "-",   # non-breaking hyphen
            "\u2012": "-",   # figure dash
            "\u2013": "-",   # en dash
            "\u2014": "-",   # em dash
            "\u2015": "-",   # horizontal bar

            # Spaces
            "\u00a0": " ",   # non-breaking space
            "\u202f": " ",   # narrow no-break space
            "\u2007": " ",   # figure space
            "\u2009": " ",   # thin space
            "\u200a": " ",   # hair space

            # Bullets / symbols
            "\u2022": "-",   # bullet
            "\u25cf": "-",   # black circle
            "\u25aa": "-",   # small square
            "\u25a0": "-",   # black square

            # Quotes
            "\u2018": "'",
            "\u2019": "'",
            "\u201a": "'",
            "\u201b": "'",
            "\u201c": '"',
            "\u201d": '"',
            "\u201e": '"',

            # Ellipsis
            "\u2026": "...",

            # Mathematical symbols commonly generated by LLMs
            "\u00d7": "x",
            "\u00f7": "/",
            "\u2264": "<=",
            "\u2265": ">=",
            "\u2260": "!=",

            # Other common symbols
            "\u2192": "->",
            "\u2190": "<-",
            "\u2194": "<->",
            "\u00b0": " deg",
            "\u00b1": "+/-",
        }

        for old, new in replacements.items():
            text = text.replace(old, new)

        # Remove remaining non-ASCII characters.
        # This is intentional because the PDF currently uses Helvetica.
        text = text.encode("ascii", errors="ignore").decode("ascii")

        return text

    @classmethod
    def _paragraph_text(cls, value):
        """
        Sanitize and HTML-escape text before passing it to ReportLab.
        """

        text = cls._sanitize_text(value)
        return html.escape(text)

    # =========================================================
    # HEADER / FOOTER
    # =========================================================

    def _header_footer(self, canvas, doc):

        canvas.saveState()

        width, height = A4

        # Header
        canvas.setFont("Helvetica-Bold", 9)

        canvas.drawString(
            20 * mm,
            height - 15 * mm,
            "AURA Fraud Intelligence",
        )

        canvas.setFont("Helvetica", 8)

        canvas.drawRightString(
            width - 20 * mm,
            height - 15 * mm,
            "AI Investigation Report",
        )

        # Footer
        canvas.setFont("Helvetica", 8)

        canvas.drawString(
            20 * mm,
            10 * mm,
            "AURA - Fraud Intelligence Platform",
        )

        canvas.drawRightString(
            width - 20 * mm,
            10 * mm,
            f"Page {doc.page}",
        )

        canvas.restoreState()

    # =========================================================
    # GENERATE PDF
    # =========================================================

    def generate(self, pipeline_result):

        if not pipeline_result:
            raise ValueError("No pipeline result supplied.")

        transaction_id = pipeline_result.get(
            "transaction_id",
            "unknown",
        )

        investigation = pipeline_result.get(
            "investigation",
            {},
        )

        ai_report = pipeline_result.get(
            "ai_report",
            {},
        )

        transaction_id = self._sanitize_text(transaction_id)

        output_path = (
            self.output_dir
            / f"AURA_investigation_{transaction_id}.pdf"
        )

        document = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=25 * mm,
            bottomMargin=18 * mm,
        )

        story = []

        # =====================================================
        # TITLE
        # =====================================================

        story.append(
            Paragraph(
                "AURA FRAUD INVESTIGATION REPORT",
                self.title_style,
            )
        )

        story.append(
            Paragraph(
                "AI-Assisted Transaction Investigation",
                self.subtitle_style,
            )
        )

        # =====================================================
        # 1. TRANSACTION OVERVIEW
        # =====================================================

        story.append(
            Paragraph(
                "1. Transaction Overview",
                self.heading_style,
            )
        )

        transaction_data = [
            [
                Paragraph("<b>Transaction ID</b>", self.body_style),
                Paragraph(
                    self._paragraph_text(transaction_id),
                    self.body_style,
                ),
            ],
            [
                Paragraph("<b>Risk Band</b>", self.body_style),
                Paragraph(
                    self._paragraph_text(
                        investigation.get(
                            "risk_band",
                            "UNKNOWN",
                        )
                    ),
                    self.body_style,
                ),
            ],
            [
                Paragraph("<b>Risk Score</b>", self.body_style),
                Paragraph(
                    self._paragraph_text(
                        investigation.get(
                            "risk_score",
                            "N/A",
                        )
                    ),
                    self.body_style,
                ),
            ],
            [
                Paragraph("<b>Fraud Probability</b>", self.body_style),
                Paragraph(
                    self._format_probability(
                        investigation.get(
                            "fraud_probability"
                        )
                    ),
                    self.body_style,
                ),
            ],
            [
                Paragraph("<b>Transaction Amount</b>", self.body_style),
                Paragraph(
                    self._paragraph_text(
                        investigation.get(
                            "amount",
                            "N/A",
                        )
                    ),
                    self.body_style,
                ),
            ],
            [
                Paragraph("<b>Investigation Flag</b>", self.body_style),
                Paragraph(
                    self._paragraph_text(
                        investigation.get(
                            "investigation_flag",
                            "N/A",
                        )
                    ),
                    self.body_style,
                ),
            ],
            [
                Paragraph("<b>Recommended Action</b>", self.body_style),
                Paragraph(
                    self._paragraph_text(
                        ai_report.get(
                            "recommended_action",
                            "N/A",
                        )
                    ),
                    self.body_style,
                ),
            ],
        ]

        table = Table(
            transaction_data,
            colWidths=[55 * mm, 105 * mm],
        )

        table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )

        story.append(table)
        story.append(Spacer(1, 8))

        # =====================================================
        # 2. EXECUTIVE SUMMARY
        # =====================================================

        story.append(
            Paragraph(
                "2. Executive Summary",
                self.heading_style,
            )
        )

        story.append(
            Paragraph(
                self._paragraph_text(
                    ai_report.get(
                        "executive_summary",
                        "No executive summary available.",
                    )
                ),
                self.body_style,
            )
        )

        # =====================================================
        # 3. RISK INTERPRETATION
        # =====================================================

        story.append(
            Paragraph(
                "3. Risk Interpretation",
                self.heading_style,
            )
        )

        risk_interpretation = ai_report.get(
            "risk_interpretation",
            [],
        )

        for item in risk_interpretation:

            clean_item = self._paragraph_text(item)

            story.append(
                Paragraph(
                    f"- {clean_item}",
                    self.body_style,
                )
            )

        # =====================================================
        # 4. INVESTIGATION EVIDENCE
        # =====================================================

        story.append(
            Paragraph(
                "4. Investigation Evidence",
                self.heading_style,
            )
        )

        evidence = ai_report.get(
            "evidence",
            [],
        )

        if evidence:

            evidence_data = [
                [
                    Paragraph(
                        "<b>Evidence Type</b>",
                        self.body_style,
                    ),
                    Paragraph(
                        "<b>Description</b>",
                        self.body_style,
                    ),
                ]
            ]

            for item in evidence:

                evidence_type = self._paragraph_text(
                    item.get(
                        "type",
                        "Evidence",
                    )
                )

                description = self._paragraph_text(
                    item.get(
                        "description",
                        "",
                    )
                )

                evidence_data.append(
                    [
                        Paragraph(
                            evidence_type,
                            self.body_style,
                        ),
                        Paragraph(
                            description,
                            self.body_style,
                        ),
                    ]
                )

            evidence_table = Table(
                evidence_data,
                colWidths=[45 * mm, 115 * mm],
                repeatRows=1,
            )

            evidence_table.setStyle(
                TableStyle(
                    [
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, 0),
                            colors.lightgrey,
                        ),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                        ("TOPPADDING", (0, 0), (-1, -1), 5),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ]
                )
            )

            story.append(evidence_table)

        else:

            story.append(
                Paragraph(
                    "No investigation evidence was recorded.",
                    self.body_style,
                )
            )

        # =====================================================
        # 5. TOP RISK FACTORS
        # =====================================================

        story.append(
            Paragraph(
                "5. Top Risk Factors",
                self.heading_style,
            )
        )

        risk_factors = ai_report.get(
            "top_risk_factors",
            [],
        )

        if risk_factors:

            risk_data = [
                [
                    Paragraph(
                        "<b>Feature</b>",
                        self.body_style,
                    ),
                    Paragraph(
                        "<b>Observed Value</b>",
                        self.body_style,
                    ),
                    Paragraph(
                        "<b>SHAP Value</b>",
                        self.body_style,
                    ),
                ]
            ]

            for factor in risk_factors:

                risk_data.append(
                    [
                        Paragraph(
                            self._paragraph_text(
                                factor.get(
                                    "feature",
                                    "",
                                )
                            ),
                            self.body_style,
                        ),
                        Paragraph(
                            self._paragraph_text(
                                factor.get(
                                    "value",
                                    "",
                                )
                            ),
                            self.body_style,
                        ),
                        Paragraph(
                            self._paragraph_text(
                                factor.get(
                                    "shap_value",
                                    "",
                                )
                            ),
                            self.body_style,
                        ),
                    ]
                )

            risk_table = Table(
                risk_data,
                colWidths=[
                    65 * mm,
                    45 * mm,
                    50 * mm,
                ],
                repeatRows=1,
            )

            risk_table.setStyle(
                TableStyle(
                    [
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, 0),
                            colors.lightgrey,
                        ),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 5),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                        ("TOPPADDING", (0, 0), (-1, -1), 5),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ]
                )
            )

            story.append(risk_table)

        else:

            story.append(
                Paragraph(
                    "No risk factors were available.",
                    self.body_style,
                )
            )

        # =====================================================
        # 6. GRAPH ANALYSIS
        # =====================================================

        story.append(
            Paragraph(
                "6. Graph Analysis",
                self.heading_style,
            )
        )

        graph_analysis = ai_report.get(
            "graph_analysis",
            {},
        )

        # Support the current InvestigationEngine graph_analysis structure.
        # Also retain backward compatibility with the older graph_analysis["data"] structure.
        graph_data = graph_analysis.get("data", {})
        if not graph_data and graph_analysis.get("graph_risk_score") is not None:
            graph_data = graph_analysis

        graph_metrics = graph_data.get(
            "graph_metrics",
            {},
        )

        if graph_data:

            graph_items = [
                (
                    "Graph Risk Score",
                    graph_data.get(
                        "graph_risk_score",
                        "N/A",
                    ),
                ),
                (
                    "Graph Risk Band",
                    graph_data.get(
                        "graph_risk_band",
                        "N/A",
                    ),
                ),
                (
                    "Transaction Count",
                    graph_metrics.get(
                        "transaction_count",
                        "N/A",
                    ),
                ),
                (
                    "Fraud Transaction Count",
                    graph_metrics.get(
                        "fraud_transaction_count",
                        "N/A",
                    ),
                ),
                (
                    "Fraud Ratio",
                    graph_metrics.get(
                        "fraud_ratio",
                        "N/A",
                    ),
                ),
            ]

            graph_table_data = [
                [
                    Paragraph(
                        "<b>Metric</b>",
                        self.body_style,
                    ),
                    Paragraph(
                        "<b>Value</b>",
                        self.body_style,
                    ),
                ]
            ]

            for label, value in graph_items:

                graph_table_data.append(
                    [
                        Paragraph(
                            self._paragraph_text(label),
                            self.body_style,
                        ),
                        Paragraph(
                            self._paragraph_text(value),
                            self.body_style,
                        ),
                    ]
                )

            graph_table = Table(
                graph_table_data,
                colWidths=[75 * mm, 85 * mm],
                repeatRows=1,
            )

            graph_table.setStyle(
                TableStyle(
                    [
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, 0),
                            colors.lightgrey,
                        ),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                        ("TOPPADDING", (0, 0), (-1, -1), 5),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ]
                )
            )

            story.append(graph_table)

            graph_reasons = graph_data.get(
                "graph_reasons",
                [],
            )

            if graph_reasons:

                story.append(Spacer(1, 6))

                story.append(
                    Paragraph(
                        "<b>Graph Reasons:</b>",
                        self.body_style,
                    )
                )

                for reason in graph_reasons:

                    story.append(
                        Paragraph(
                            f"- {self._paragraph_text(reason)}",
                            self.body_style,
                        )
                    )

        else:

            story.append(
                Paragraph(
                    "No graph analysis was available.",
                    self.body_style,
                )
            )

        # =====================================================
        # 7. AI INVESTIGATION ANALYSIS
        # =====================================================

        story.append(PageBreak())

        story.append(
            Paragraph(
                "7. AI Investigation Analysis",
                self.heading_style,
            )
        )

        ai_analysis = ai_report.get(
            "ai_analysis",
            "",
        )

        if ai_analysis:

            self._add_ai_analysis(
                story,
                ai_analysis,
            )

        else:

            story.append(
                Paragraph(
                    "No AI analysis was available.",
                    self.body_style,
                )
            )

        # =====================================================
        # 8. INVESTIGATOR CONCLUSION
        # =====================================================

        story.append(
            Paragraph(
                "8. Investigator Conclusion",
                self.heading_style,
            )
        )

        conclusion = ai_report.get(
            "investigator_conclusion",
            "No conclusion available.",
        )

        story.append(
            Paragraph(
                self._paragraph_text(conclusion),
                self.body_style,
            )
        )

        # =====================================================
        # BUILD PDF
        # =====================================================

        document.build(
            story,
            onFirstPage=self._header_footer,
            onLaterPages=self._header_footer,
        )

        return str(output_path)

    # =========================================================
    # AI ANALYSIS FORMATTER
    # =========================================================

    def _add_ai_analysis(self, story, ai_analysis):

        """
        Converts basic AI markdown into clean ReportLab content.

        Handles:
        - headings
        - bullet points
        - numbered lists
        - simple markdown tables
        - bold markdown
        """

        lines = str(ai_analysis).splitlines()

        table_buffer = []

        def flush_table():

            nonlocal table_buffer

            if not table_buffer:
                return

            rows = []

            for line in table_buffer:

                clean_line = line.strip()

                if not clean_line.startswith("|"):
                    continue

                if not clean_line.endswith("|"):
                    clean_line += "|"

                cells = [
                    cell.strip()
                    for cell in clean_line.strip("|").split("|")
                ]

                # Ignore markdown separator rows
                if cells and all(
                    re.fullmatch(
                        r"[:\- ]+",
                        cell or "-",
                    )
                    for cell in cells
                ):
                    continue

                rows.append(cells)

            if rows:

                max_columns = max(
                    len(row)
                    for row in rows
                )

                normalized_rows = []

                for row in rows:

                    row = row + [""] * (
                        max_columns - len(row)
                    )

                    normalized_rows.append(
                        [
                            Paragraph(
                                self._paragraph_text(cell),
                                self.small_style,
                            )
                            for cell in row
                        ]
                    )

                column_width = (
                    160 * mm
                    / max_columns
                )

                table = Table(
                    normalized_rows,
                    colWidths=[
                        column_width
                    ] * max_columns,
                    repeatRows=1,
                )

                table.setStyle(
                    TableStyle(
                        [
                            (
                                "GRID",
                                (0, 0),
                                (-1, -1),
                                0.5,
                                colors.grey,
                            ),
                            (
                                "BACKGROUND",
                                (0, 0),
                                (-1, 0),
                                colors.lightgrey,
                            ),
                            (
                                "VALIGN",
                                (0, 0),
                                (-1, -1),
                                "TOP",
                            ),
                            (
                                "LEFTPADDING",
                                (0, 0),
                                (-1, -1),
                                5,
                            ),
                            (
                                "RIGHTPADDING",
                                (0, 0),
                                (-1, -1),
                                5,
                            ),
                            (
                                "TOPPADDING",
                                (0, 0),
                                (-1, -1),
                                4,
                            ),
                            (
                                "BOTTOMPADDING",
                                (0, 0),
                                (-1, -1),
                                4,
                            ),
                        ]
                    )
                )

                story.append(table)
                story.append(Spacer(1, 6))

            table_buffer = []

        for raw_line in lines:

            line = raw_line.strip()

            # -------------------------------------------------
            # Empty line
            # -------------------------------------------------

            if not line:

                flush_table()

                story.append(
                    Spacer(1, 4)
                )

                continue

            # -------------------------------------------------
            # Markdown table
            # -------------------------------------------------

            if line.startswith("|"):

                table_buffer.append(line)
                continue

            flush_table()

            # -------------------------------------------------
            # Markdown headings
            # -------------------------------------------------

            if line.startswith("#"):

                heading = line.lstrip("#").strip()

                heading = heading.replace(
                    "**",
                    "",
                )

                story.append(
                    Paragraph(
                        self._paragraph_text(heading),
                        self.heading_style,
                    )
                )

                continue

            # -------------------------------------------------
            # Bullet points
            # -------------------------------------------------

            if line.startswith("- ") or line.startswith("* "):

                bullet = line[2:].strip()

                bullet = bullet.replace(
                    "**",
                    "",
                )

                story.append(
                    Paragraph(
                        f"- {self._paragraph_text(bullet)}",
                        self.body_style,
                    )
                )

                continue

            # -------------------------------------------------
            # Numbered lists
            # -------------------------------------------------

            numbered_match = re.match(
                r"^(\d+)\.\s+(.*)$",
                line,
            )

            if numbered_match:

                number = numbered_match.group(1)
                content = numbered_match.group(2)

                content = content.replace(
                    "**",
                    "",
                )

                story.append(
                    Paragraph(
                        f"{number}. "
                        f"{self._paragraph_text(content)}",
                        self.body_style,
                    )
                )

                continue

            # -------------------------------------------------
            # Bold markdown
            # -------------------------------------------------

            line = line.replace(
                "**",
                "",
            )

            # -------------------------------------------------
            # Inline code markers
            # -------------------------------------------------

            line = line.replace(
                "`",
                "",
            )

            story.append(
                Paragraph(
                    self._paragraph_text(line),
                    self.body_style,
                )
            )

        flush_table()

    # =========================================================
    # FORMAT PROBABILITY
    # =========================================================

    @staticmethod
    def _format_probability(value):

        if value is None:
            return "N/A"

        try:

            return f"{float(value) * 100:.2f}%"

        except (ValueError, TypeError):

            return str(value)